In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import fix_yahoo_finance as yf
import datetime
pd.core.common.is_list_like = pd.api.types.is_list_like
import pandas_datareader.data as web
from pandas.tseries.holiday import USFederalHolidayCalendar
from pandas.tseries.offsets import CustomBusinessDay

In [2]:
stock_price=[]

#datetime.datetime is a data type within the datetime module
# end day is today
today = datetime.datetime.today()
today.strftime('%Y-%m-%d')

# start day is last business day
US_BUSINESS_DAY = CustomBusinessDay(calendar=USFederalHolidayCalendar())
lastBusDay = today - 6 * US_BUSINESS_DAY
lastBusDay.strftime('%Y-%m-%d')

stocks = ["^GSPC", "TSLA", "GOOG", "AAPL", "AMZN", "FB", "MSFT"]

for stock in stocks:
    price = web.DataReader(stock, 'yahoo', lastBusDay, today)
    price['Stock'] = stock
    stock_price.append(price)
    
stock_price

[                   High          Low         Open        Close      Volume  \
 Date
 2018-08-07  2863.429932  2855.919922  2855.919922  2858.449951  3162770000
 2018-08-08  2862.439941  2853.090088  2856.790039  2857.699951  2972200000
 2018-08-09  2862.479980  2851.979980  2857.189941  2853.580078  3047050000
 2018-08-10  2842.199951  2825.810059  2838.899902  2833.280029  3256040000
 2018-08-13  2843.399902  2819.879883  2835.459961  2821.929932  3158450000
 2018-08-14  2843.110107  2826.580078  2827.879883  2839.959961  1733260850

               Adj Close  Stock
 Date
 2018-08-07  2858.449951  ^GSPC
 2018-08-08  2857.699951  ^GSPC
 2018-08-09  2853.580078  ^GSPC
 2018-08-10  2833.280029  ^GSPC
 2018-08-13  2821.929932  ^GSPC
 2018-08-14  2839.959961  ^GSPC  ,
                   High         Low        Open       Close    Volume  \
 Date
 2018-08-07  387.459991  339.149994  343.839996  379.570007  30875800
 2018-08-08  382.640015  367.119995  369.089996  370.339996  24571200
 2018-08-09  367.010010  345.730011  365.549988  352.450012  17103700
 2018-08-10  360.000000  346.000000  354.000000  355.489990  11552000
 2018-08-13  363.190002  349.019989  361.130005  356.410004  10450200
 2018-08-14  359.199493  347.100006  358.450012  347.640015   6841818

              Adj Close Stock
 Date
 2018-08-07  379.570007  TSLA
 2018-08-08  370.339996  TSLA
 2018-08-09  352.450012  TSLA
 2018-08-10  355.489990  TSLA
 2018-08-13  356.410004  TSLA
 2018-08-14  347.640015  TSLA  ,
                    High          Low         Open        Close   Volume  \
 Date
 2018-08-07  1251.170044  1236.170044  1237.000000  1242.219971  1494000
 2018-08-08  1256.500000  1238.008057  1240.469971  1245.609985  1370300
 2018-08-09  1255.541992  1246.010010  1249.900024  1249.099976   841800
 2018-08-10  1245.694946  1232.000000  1243.000000  1237.609985  1108700
 2018-08-13  1249.272949  1233.640991  1236.979980  1235.010010   958100
 2018-08-14  1245.854980  1225.109985  1235.189941  1242.099976  1101110

               Adj Close Stock
 Date
 2018-08-07  1242.219971  GOOG
 2018-08-08  1245.609985  GOOG
 2018-08-09  1249.099976  GOOG
 2018-08-10  1237.609985  GOOG
 2018-08-13  1235.010010  GOOG
 2018-08-14  1242.099976  GOOG  ,
                   High         Low        Open       Close      Volume  \
 Date
 2018-08-07  209.500000  206.759995  209.320007  207.110001  25587400.0
 2018-08-08  207.809998  204.520004  206.050003  207.250000  22525500.0
 2018-08-09  209.779999  207.199997  207.279999  208.880005  23469200.0
 2018-08-10  209.100006  206.669998  207.360001  207.529999  24611200.0
 2018-08-13  210.949997  207.699997  207.699997  208.869995  25869100.0
 2018-08-14  210.559998  208.259995  210.154999  209.750000  18847311.0

              Adj Close Stock
 Date
 2018-08-07  206.386185  AAPL
 2018-08-08  206.525696  AAPL
 2018-08-09  208.149994  AAPL
 2018-08-10  207.529999  AAPL
 2018-08-13  208.869995  AAPL
 2018-08-14  209.750000  AAPL  ,
                    High          Low         Open        Close   Volume  \
 Date
 2018-08-07  1869.719971  1846.270020  1854.530029  1862.479980  3377500
 2018-08-08  1891.510010  1854.500000  1861.000000  1886.520020  3963000
 2018-08-09  1914.569946  1877.479980  1882.000000  1898.520020  4849900
 2018-08-10  1899.500000  1878.209961  1888.510010  1886.300049  3639900
 2018-08-13  1925.000000  1893.670044  1898.500000  1896.199951  5512600
 2018-08-14  1921.010010  1900.000000  1919.390015  1919.650024  3684445

               Adj Close Stock
 Date
 2018-08-07  1862.479980  AMZN
 2018-08-08  1886.520020  AMZN
 2018-08-09  1898.520020  AMZN
 2018-08-10  1886.300049  AMZN
 2018-08-13  1896.199951  AMZN
 2018-08-14  1919.650024  AMZN  ,
                   High         Low        Open       Close    Volume  \
 Date
 2018-08-07  188.300003  183.720001  186.500000  183.809998  33398600
 2018-08-08  186.850006  183.759995  184.750000  185.179993  22205200
 2018-08-09  186.570007  182.479996  185.850006  183.089996  19696700
 2018-08-10  182.100006  179.419998  182.039993  180.259995  21500400
 2018-08-13  182.610001  178.899994  180.100006  180.050003  17369400
 2018-08-14  181.990005  178.619995  180.710007  181.110001  19090274

              Adj Close Stock
 Date
 2018-08-07  183.809998    FB
 2018-08-08  185.179993    FB
 2018-08-09  183.089996    FB
 2018-08-10  180.259995    FB
 2018-08-13  180.050003    FB
 2018-08-14  181.110001    FB  ,
                   High         Low        Open       Close    Volume  \
 Date
 2018-08-07  109.099998  108.169998  108.559998  108.879997  16080200
 2018-08-08  109.750000  108.760002  109.330002  109.489998  15487500
 2018-08-09  110.160004  109.599998  109.709999  109.669998  13660400
 2018-08-10  109.690002  108.379997  109.419998  109.000000  18183700
 2018-08-13  109.580002  108.099998  109.239998  108.209999  18472500
 2018-08-14  109.750000  108.040001  108.559998  109.559998  16636919

              Adj Close Stock
 Date
 2018-08-07  108.879997  MSFT
 2018-08-08  109.489998  MSFT
 2018-08-09  109.669998  MSFT
 2018-08-10  109.000000  MSFT
 2018-08-13  108.209999  MSFT
 2018-08-14  109.559998  MSFT  ]

In [3]:
# end day is today
today = datetime.datetime.today()
today.strftime('%Y-%m-%d')
# start day is 5 business days ago
US_BUSINESS_DAY = CustomBusinessDay(calendar=USFederalHolidayCalendar())
lastBusDay = today - 6 * US_BUSINESS_DAY
lastBusDay.strftime('%Y-%m-%d')

'2018-08-06'

# SP

In [4]:
# get stock price of today and last five business days
SP = web.DataReader('^GSPC', 'yahoo', lastBusDay, today)
SP['Stock'] = ['SP-5', 'SP-4', 'SP-3', 'SP-2', 'SP-1', 'SP-0']
SP = SP.iloc[::-1]
# generate dollar value of movement between adjacent business days
SP['Mov $'] = round(-SP['Adj Close'].diff().shift(-1), 2)
# generate percentage of movement between adjacent business days
SP['Mov %'] = SP['Mov $']/SP['Adj Close'].shift(-1)
SP['Mov %'] = pd.Series(["{0:.2f}%".format(X * 100) for X in SP['Mov %']], index = SP.index)
SP

,High,Low,Open,Close,Volume,Adj Close,Stock,Mov $,Mov %
Date,,,,,,,,,
2018-08-14,2843.110107,2826.580078,2827.879883,2839.959961,1733260850,2839.959961,SP-0,18.03,0.64%
2018-08-13,2843.399902,2819.879883,2835.459961,2821.929932,3158450000,2821.929932,SP-1,-11.35,-0.40%
2018-08-10,2842.199951,2825.810059,2838.899902,2833.280029,3256040000,2833.280029,SP-2,-20.30,-0.71%
2018-08-09,2862.479980,2851.979980,2857.189941,2853.580078,3047050000,2853.580078,SP-3,-4.12,-0.14%
2018-08-08,2862.439941,2853.090088,2856.790039,2857.699951,2972200000,2857.699951,SP-4,-0.75,-0.03%
2018-08-07,2863.429932,2855.919922,2855.919922,2858.449951,3162770000,2858.449951,SP-5,NaN,nan%

In [5]:
# Movement $ = Adj Close(2018-08-14) - Adj Close(2018-08-13)
SP['Mov $']

Date
2018-08-14    18.03
2018-08-13   -11.35
2018-08-10   -20.30
2018-08-09    -4.12
2018-08-08    -0.75
2018-08-07      NaN
Name: Mov $, dtype: float64

In [6]:
SP['Adj Close']

Date
2018-08-14    2839.959961
2018-08-13    2821.929932
2018-08-10    2833.280029
2018-08-09    2853.580078
2018-08-08    2857.699951
2018-08-07    2858.449951
Name: Adj Close, dtype: float64

In [7]:
# make it lags for one business day
SP['Adj Close'].shift(-1)

Date
2018-08-14    2821.929932
2018-08-13    2833.280029
2018-08-10    2853.580078
2018-08-09    2857.699951
2018-08-08    2858.449951
2018-08-07            NaN
Name: Adj Close, dtype: float64

In [8]:
# Movement % = (Adj Close(2018-08-14) - Adj Close(2018-08-13)) / Adj Close(2018-08-13)
SP['Mov $']/SP['Adj Close'].shift(-1)

Date
2018-08-14    0.006389
2018-08-13   -0.004006
2018-08-10   -0.007114
2018-08-09   -0.001442
2018-08-08   -0.000262
2018-08-07         NaN
dtype: float64

# TSLA

In [9]:
# get stock price of today and last five business days
TSLA = web.DataReader('TSLA', 'yahoo', lastBusDay, today)
TSLA['Stock'] = ['TSLA-5', 'TSLA-4', 'TSLA-3', 'TSLA-2', 'TSLA-1', 'TSLA-0']
TSLA = TSLA.iloc[::-1]
# generate dollar value of movement between adjacent business days
TSLA['Mov $'] = round(-TSLA['Adj Close'].diff().shift(-1), 2)
# generate percentage of movement between adjacent business days
TSLA['Mov %'] = TSLA['Mov $']/TSLA['Adj Close'].shift(-1)
TSLA['Mov %'] = pd.Series(["{0:.2f}%".format(X * 100) for X in TSLA['Mov %']], index = TSLA.index)
# movement percentage get rid of market fluctuation
TSLA['Mov_noSP %'] = TSLA['Mov $']/TSLA['Adj Close'].shift(-1) - SP['Mov $']/SP['Adj Close'].shift(-1)
TSLA['Mov_noSP %'] = pd.Series(["{0:.2f}%".format(X * 100) for X in TSLA['Mov_noSP %']], index = TSLA.index)
TSLA

,High,Low,Open,Close,Volume,Adj Close,Stock,Mov $,Mov %,Mov_noSP %
Date,,,,,,,,,,
2018-08-14,359.199493,347.100006,358.450012,347.640015,6841818,347.640015,TSLA-0,-8.77,-2.46%,-3.10%
2018-08-13,363.190002,349.019989,361.130005,356.410004,10450200,356.410004,TSLA-1,0.92,0.26%,0.66%
2018-08-10,360.000000,346.000000,354.000000,355.489990,11552000,355.489990,TSLA-2,3.04,0.86%,1.57%
2018-08-09,367.010010,345.730011,365.549988,352.450012,17103700,352.450012,TSLA-3,-17.89,-4.83%,-4.69%
2018-08-08,382.640015,367.119995,369.089996,370.339996,24571200,370.339996,TSLA-4,-9.23,-2.43%,-2.41%
2018-08-07,387.459991,339.149994,343.839996,379.570007,30875800,379.570007,TSLA-5,NaN,nan%,nan%

# GOOG

In [10]:
# get stock price of today and last five business days
GOOG = web.DataReader('GOOG', 'yahoo', lastBusDay, today)
GOOG['Stock'] = ['GOOG-5', 'GOOG-4', 'GOOG-3', 'GOOG-2', 'GOOG-1', 'GOOG-0']
GOOG = GOOG.iloc[::-1]
# generate dollar value of movement between adjacent business days
GOOG['Mov $'] = round(-GOOG['Adj Close'].diff().shift(-1), 2)
# generate percentage of movement between adjacent business days
GOOG['Mov %'] = GOOG['Mov $']/GOOG['Adj Close'].shift(-1)
GOOG['Mov %'] = pd.Series(["{0:.2f}%".format(X * 100) for X in GOOG['Mov %']], index = GOOG.index)
# movement percentage get rid of market fluctuation
GOOG['Mov_noSP %'] = GOOG['Mov $']/GOOG['Adj Close'].shift(-1) - SP['Mov $']/SP['Adj Close'].shift(-1)
GOOG['Mov_noSP %'] = pd.Series(["{0:.2f}%".format(X * 100) for X in GOOG['Mov_noSP %']], index = GOOG.index)
GOOG

,High,Low,Open,Close,Volume,Adj Close,Stock,Mov $,Mov %,Mov_noSP %
Date,,,,,,,,,,
2018-08-14,1245.854980,1225.109985,1235.189941,1242.099976,1101110,1242.099976,GOOG-0,7.09,0.57%,-0.06%
2018-08-13,1249.272949,1233.640991,1236.979980,1235.010010,958100,1235.010010,GOOG-1,-2.60,-0.21%,0.19%
2018-08-10,1245.694946,1232.000000,1243.000000,1237.609985,1108700,1237.609985,GOOG-2,-11.49,-0.92%,-0.21%
2018-08-09,1255.541992,1246.010010,1249.900024,1249.099976,841800,1249.099976,GOOG-3,3.49,0.28%,0.42%
2018-08-08,1256.500000,1238.008057,1240.469971,1245.609985,1370300,1245.609985,GOOG-4,3.39,0.27%,0.30%
2018-08-07,1251.170044,1236.170044,1237.000000,1242.219971,1494000,1242.219971,GOOG-5,NaN,nan%,nan%

# AAPL

In [11]:
# get stock price of today and last five business days
AAPL = web.DataReader('AAPL', 'yahoo', lastBusDay, today)
AAPL['Stock'] = ['AAPL-5', 'AAPL-4', 'AAPL-3', 'AAPL-2', 'AAPL-1', 'AAPL-0']
AAPL = AAPL.iloc[::-1]
# generate dollar value of movement between adjacent business days
AAPL['Mov $'] = round(-AAPL['Adj Close'].diff().shift(-1), 2)
# generate percentage of movement between adjacent business days
AAPL['Mov %'] = AAPL['Mov $']/AAPL['Adj Close'].shift(-1)
AAPL['Mov %'] = pd.Series(["{0:.2f}%".format(X * 100) for X in AAPL['Mov %']], index = AAPL.index)
# movement percentage get rid of market fluctuation
AAPL['Mov_noSP %'] = AAPL['Mov $']/AAPL['Adj Close'].shift(-1) - SP['Mov $']/SP['Adj Close'].shift(-1)
AAPL['Mov_noSP %'] = pd.Series(["{0:.2f}%".format(X * 100) for X in AAPL['Mov_noSP %']], index = AAPL.index)
AAPL

,High,Low,Open,Close,Volume,Adj Close,Stock,Mov $,Mov %,Mov_noSP %
Date,,,,,,,,,,
2018-08-14,210.559998,208.259995,210.154999,209.750000,18847311.0,209.750000,AAPL-0,0.88,0.42%,-0.22%
2018-08-13,210.949997,207.699997,207.699997,208.869995,25869100.0,208.869995,AAPL-1,1.34,0.65%,1.05%
2018-08-10,209.100006,206.669998,207.360001,207.529999,24611200.0,207.529999,AAPL-2,-0.62,-0.30%,0.41%
2018-08-09,209.779999,207.199997,207.279999,208.880005,23469200.0,208.149994,AAPL-3,1.62,0.78%,0.93%
2018-08-08,207.809998,204.520004,206.050003,207.250000,22525500.0,206.525696,AAPL-4,0.14,0.07%,0.09%
2018-08-07,209.500000,206.759995,209.320007,207.110001,25587400.0,206.386185,AAPL-5,NaN,nan%,nan%

# AMZN

In [12]:
# get stock price of today and last five business days
AMZN = web.DataReader('AMZN', 'yahoo', lastBusDay, today)
AMZN['Stock'] = ['AMZN-5', 'AMZN-4', 'AMZN-3', 'AMZN-2', 'AMZN-1', 'AMZN-0']
AMZN = AMZN.iloc[::-1]
# generate dollar value of movement between adjacent business days
AMZN['Mov $'] = round(-AMZN['Adj Close'].diff().shift(-1), 2)
# generate percentage of movement between adjacent business days
AMZN['Mov %'] = AMZN['Mov $']/AMZN['Adj Close'].shift(-1)
AMZN['Mov %'] = pd.Series(["{0:.2f}%".format(X * 100) for X in AMZN['Mov %']], index = AMZN.index)
# movement percentage get rid of market fluctuation
AMZN['Mov_noSP %'] = AMZN['Mov $']/AMZN['Adj Close'].shift(-1) - SP['Mov $']/SP['Adj Close'].shift(-1)
AMZN['Mov_noSP %'] = pd.Series(["{0:.2f}%".format(X * 100) for X in AMZN['Mov_noSP %']], index = AMZN.index)
AMZN

,High,Low,Open,Close,Volume,Adj Close,Stock,Mov $,Mov %,Mov_noSP %
Date,,,,,,,,,,
2018-08-14,1921.010010,1900.000000,1919.390015,1919.650024,3684445,1919.650024,AMZN-0,23.45,1.24%,0.60%
2018-08-13,1925.000000,1893.670044,1898.500000,1896.199951,5512600,1896.199951,AMZN-1,9.90,0.52%,0.93%
2018-08-10,1899.500000,1878.209961,1888.510010,1886.300049,3639900,1886.300049,AMZN-2,-12.22,-0.64%,0.07%
2018-08-09,1914.569946,1877.479980,1882.000000,1898.520020,4849900,1898.520020,AMZN-3,12.00,0.64%,0.78%
2018-08-08,1891.510010,1854.500000,1861.000000,1886.520020,3963000,1886.520020,AMZN-4,24.04,1.29%,1.32%
2018-08-07,1869.719971,1846.270020,1854.530029,1862.479980,3377500,1862.479980,AMZN-5,NaN,nan%,nan%

# FB

In [13]:
# get stock price of today and last five business days
FB = web.DataReader('FB', 'yahoo', lastBusDay, today)
FB['Stock'] = ['FB-5', 'FB-4', 'FB-3', 'FB-2', 'FB-1', 'FB-0']
FB = FB.iloc[::-1]
# generate dollar value of movement between adjacent business days
FB['Mov $'] = round(-FB['Adj Close'].diff().shift(-1), 2)
# generate percentage of movement between adjacent business days
FB['Mov %'] = FB['Mov $']/FB['Adj Close'].shift(-1)
FB['Mov %'] = pd.Series(["{0:.2f}%".format(X * 100) for X in FB['Mov %']], index = FB.index)
# movement percentage get rid of market fluctuation
FB['Mov_noSP %'] = FB['Mov $']/FB['Adj Close'].shift(-1) - SP['Mov $']/SP['Adj Close'].shift(-1)
FB['Mov_noSP %'] = pd.Series(["{0:.2f}%".format(X * 100) for X in FB['Mov_noSP %']], index = FB.index)
FB

,High,Low,Open,Close,Volume,Adj Close,Stock,Mov $,Mov %,Mov_noSP %
Date,,,,,,,,,,
2018-08-14,181.990005,178.619995,180.710007,181.110001,19090274,181.110001,FB-0,1.06,0.59%,-0.05%
2018-08-13,182.610001,178.899994,180.100006,180.050003,17369400,180.050003,FB-1,-0.21,-0.12%,0.28%
2018-08-10,182.100006,179.419998,182.039993,180.259995,21500400,180.259995,FB-2,-2.83,-1.55%,-0.83%
2018-08-09,186.570007,182.479996,185.850006,183.089996,19696700,183.089996,FB-3,-2.09,-1.13%,-0.98%
2018-08-08,186.850006,183.759995,184.750000,185.179993,22205200,185.179993,FB-4,1.37,0.75%,0.77%
2018-08-07,188.300003,183.720001,186.500000,183.809998,33398600,183.809998,FB-5,NaN,nan%,nan%

# MSFT

In [14]:
# get stock price of today and last five business days
MSFT = web.DataReader('MSFT', 'yahoo', lastBusDay, today)
MSFT['Stock'] = ['MSFT-5', 'MSFT-4', 'MSFT-3', 'MSFT-2', 'MSFT-1', 'MSFT-0']
MSFT = MSFT.iloc[::-1]
# generate dollar value of movement between adjacent business days
MSFT['Mov $'] = round(-MSFT['Adj Close'].diff().shift(-1), 2)
# generate percentage of movement between adjacent business days
MSFT['Mov %'] = MSFT['Mov $']/MSFT['Adj Close'].shift(-1)
MSFT['Mov %'] = pd.Series(["{0:.2f}%".format(X * 100) for X in MSFT['Mov %']], index = MSFT.index)
# movement percentage get rid of market fluctuation
MSFT['Mov_noSP %'] = MSFT['Mov $']/MSFT['Adj Close'].shift(-1) - SP['Mov $']/SP['Adj Close'].shift(-1)
MSFT['Mov_noSP %'] = pd.Series(["{0:.2f}%".format(X * 100) for X in MSFT['Mov_noSP %']], index = MSFT.index)
MSFT

,High,Low,Open,Close,Volume,Adj Close,Stock,Mov $,Mov %,Mov_noSP %
Date,,,,,,,,,,
2018-08-14,109.750000,108.040001,108.559998,109.559998,16636919,109.559998,MSFT-0,1.35,1.25%,0.61%
2018-08-13,109.580002,108.099998,109.239998,108.209999,18472500,108.209999,MSFT-1,-0.79,-0.72%,-0.32%
2018-08-10,109.690002,108.379997,109.419998,109.000000,18183700,109.000000,MSFT-2,-0.67,-0.61%,0.10%
2018-08-09,110.160004,109.599998,109.709999,109.669998,13660400,109.669998,MSFT-3,0.18,0.16%,0.31%
2018-08-08,109.750000,108.760002,109.330002,109.489998,15487500,109.489998,MSFT-4,0.61,0.56%,0.59%
2018-08-07,109.099998,108.169998,108.559998,108.879997,16080200,108.879997,MSFT-5,NaN,nan%,nan%

# Consolation

In [15]:
stock_price_conso = pd.concat([SP, TSLA, GOOG, AAPL, AMZN, FB, MSFT])
stock_price_conso.to_csv('stock_price_conso.csv', encoding='utf-8-sig', index=False)